"""Regenerates services/german_area_codes.py from the Bundesnetzagentur's
Vorwahlverzeichnis - the list of all German area codes
(Ortsnetzkennzahlen), which services/phone.py needs to tell where a
landline number's area code ends ("089 1234567", "07151 123456").

Area codes practically never change; run this only if the
Bundesnetzagentur publishes a new list. Download and unpack the ZIP
"Vorwahlverzeichnis (VwV)" from

    https://www.bundesnetzagentur.de/DE/Fachthemen/Telekommunikation/Nummerierung/ONRufnr/Einteilung_ONB/start.html

then pass the CSV it contains (columns: Ortsnetzkennzahl; Ortsnetzname;
KennzeichenAktiv):

    uv run python scripts/generate_area_codes.py NVONB.INTERNET.20220727.ONB.csv

A generated Python module rather than a data file read at runtime, so the
PyInstaller build needs no extra entry for it, and rather than a
phone-number library, which would be a large dependency for this one table.
"""

import csv
import sys
import textwrap
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_TARGET = _REPO_ROOT / "src/klientenverwaltung/services/german_area_codes.py"

_TEMPLATE = '''"""German area codes (Ortsnetzkennzahlen), without the leading 0.

Generated by scripts/generate_area_codes.py from the Bundesnetzagentur's
Vorwahlverzeichnis ({source}) - do not edit by hand.
{count} active codes, two to five digits long. No code is the beginning of
another one, except 212 (Solingen) and 2129 (Haan) - so the longest
matching code is the area code of a number.
"""

_CODES = """
{codes}
"""

AREA_CODES: frozenset[str] = frozenset(_CODES.split())
'''


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    source = Path(sys.argv[1])
    # Only the digits of the first column are used, so place names that
    # do not decode cleanly do no harm.
    lines = source.read_text(encoding="utf-8", errors="replace").splitlines()
    codes = sorted(
        row[0]
        for row in csv.reader(lines, delimiter=";")
        if len(row) >= 3 and row[0].isdigit() and row[2] == "1"
    )
    if not 5000 < len(codes) < 5500 or not all(2 <= len(code) <= 5 for code in codes):
        sys.exit(f"Unerwarteter Inhalt: {len(codes)} Ortsnetzkennzahlen in {source}")
    wrapped = textwrap.fill(
        " ".join(codes), width=84, initial_indent="    ", subsequent_indent="    "
    )
    _TARGET.write_text(
        _TEMPLATE.format(source=source.name, count=len(codes), codes=wrapped),
        encoding="utf-8",
        newline="\n",
    )
    print(f"{len(codes)} Ortsnetzkennzahlen nach {_TARGET} geschrieben.")


if __name__ == "__main__":
    main()
